# Temporary SwiftLint config for testing - allows everything
disabled_rules:
  - trailing_comma
  - vertical_whitespace
  - identifier_name
  - line_length
  - trailing_newline
  - file_header
  - force_unwrapping

excluded:
  - .build
  - Pods
  - .swiftpm